// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StocksCourseworkWebapp.Contexts;

namespace StocksCourseworkWebapp.Migrations
{
    [DbContext(typeof(WebAppContext))]
    [Migration("20210117145843_addUserHoldingsTable")]
    partial class addUserHoldingsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("StocksCourseworkWebapp.Models.DatabaseObjects.AccountDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<bool>("loggedIn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AccountDetails");
                });

            modelBuilder.Entity("StocksCourseworkWebapp.Models.DatabaseObjects.UserHoldings", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceBought")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceSold")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimeBought")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("UserHoldings");
                });
#pragma warning restore 612, 618
        }
    }
}
