// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StocksCourseworkWebapp.Contexts;

namespace StocksCourseworkWebapp.Migrations
{
    [DbContext(typeof(WebAppContext))]
    [Migration("20210123221150_changeIdStringtoInt")]
    partial class changeIdStringtoInt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("StocksCourseworkWebapp.Models.DatabaseObjects.AccountDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccountBalanceAvailable")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccountBalanceConverted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccountDetails");
                });

            modelBuilder.Entity("StocksCourseworkWebapp.Models.DatabaseObjects.UserHoldings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceBought")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceSold")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimeBought")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("UserHoldings");
                });
#pragma warning restore 612, 618
        }
    }
}
